### ISSUE TITLE
Realtime Markdown Convertor tiddler

### ISSUE THREAD

**Issue by arunnbabu81** [cdaven/tiddlywiki-stuff#2]
As I asked in the talk tiddlywiki forum (https://talk.tiddlywiki.org/t/first-version-of-markdown-export-plugin/3324/20?u=arunnbabu81)

Can there be an additional option like a `Realtime Markdown Convertor tiddler` 
1. At the top of this convertor tiddler,  there shall be a `tiddler selector` with `search box` (where we can type the tiddler name) or `select widget ` option to select the tiddler converted to be markdown.
2. Once the tiddler is selected, a side by side editor opens up below the selector showing the wikitext format on the left side and markdown format on the right side.
3. At the bottom, there shall be a `export as md` or `copy to clipboard` buttons.

Is it doable?

**Comment by cdaven** [comment]
Could you explain what this would be useful for? (But it seems like something I personally don't want to put in the effort to develop.)

**Comment by arunnbabu81** [comment]
> Could you explain what this would be useful for? (But it seems like something I personally don't want to put in the effort to develop.)

It would be easy to copy and paste tiddler contents to other apps which support markdown. 
Even if there is no realtime converter tiddler, if a viewtoolbar button to copy the tiddler contents in markdown format is provided, that would be sufficient.

**Comment by cdaven** [comment]
A toolbar button for copying and editing was implemented in 0.6.0
