### ISSUE TITLE
Table export ignores thead tags

### ISSUE THREAD

**Issue by michaeljmcd** [cdaven/tiddlywiki-stuff#5]
The end result is that if you export a tiddler with a table rendered with headers under a `thead` row, the entire row is absent from the exported Markdown.

Steps to reproduce:

1. Import [Table Export Example.json](https://github.com/cdaven/tiddlywiki-stuff/files/15324652/Table.Export.Example.json) as a tiddler in the example wiki at https://cdaven.github.io/tiddlywiki/index.html
2. Click the export button and choose "Markdown".

The rendered markdown will render:

```
Here is an example:

| ASDF |
|------|
```

Which turns the first data row into the header and removes the header entirely.

This isn't really an issue when using WikiText because TiddlyWiki places header rows under `tbody`, but if you use the Markdown plugin and use Markdown headers, you'll get header rows in `thead`. (As a digression, I use Markdown export on Markdown tiddlers to handle transclusion, widgets, and wiki links that are allowed in Markdown tiddlers).

**Comment by cdaven** [comment]
Thanks for the bug report. I understand the problem, but I cannot make any promises about fixing it anytime soon.

**Comment by michaeljmcd** [comment]
I took a look at the code and I think I see how to make the change. I will post a PR.
