### ISSUE TITLE
Support for PowerShell building on mac

### ISSUE THREAD

**Issue by hissohathair** [cdaven/tiddlywiki-stuff#6]
I've made some (small) patches to the install and test PowerShell scripts so that it runs on Mac (and probably Linux as well, but haven't tested yet).

Are you interested in a PR with the changes?

**Comment by cdaven** [comment]
Awesome! The scripts were never really intended to work for other people, since I didn't expect anyone else to want to run them... Feel free to create a PR and I will review it.

**Comment by hissohathair** [comment]
PR created. Hope it's OK I don't do this very often. LMK if I need to fix anything.

And thanks for creating and sharing -- have been using it a fair bit. I made some local changes to support Obsidian but it's a bit non-standard in places so I'll check and see if there's anything nice and general that might be useful.
